### ISSUE TITLE
kind: Custom("Max retries")

### ISSUE THREAD

**Issue by weimumu** [HardhatChad/ore#11]
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ore-cli-0.4.1/src/register.rs:27:14:
Transaction failed: Error { request: None, kind: Custom("Max retries") }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by giannsaicpibot99** [comment]
I have the same issue when running 
```
ore \
    --rpc https://api.mainnet-beta.solana.com \
    --keypair ~/.config/solana/id.json \
    --priority-fee 1 \
    mine \
    --threads 4
```

Here is all of the output

```
Generating challenge...
Attempt: 0
4nd4Ubys1T4TUX42aPX3UUniQeJoYxbUXkfkp5pK1C2CRetEuBQ8Sfvxoz1YVHdv4am7fF2vnw9JxYwZWUpDwQm3
Confirms: [None]
Confirms: [None]
Confirms: [None]
Confirms: [None]
Transaction did not land
Attempt: 1
3roTiicQD9xdnbGfyDMyPfvBtGa1kWeZwa9RYhuSthE5XHHyftYpPf11vyHRnnsoP6ojWbAfsuGJ2rny7HS6ERxy
Confirms: [None, None]
Confirms: [None, None]
Confirms: [None, None]
Confirms: [None, None]
Transaction did not land
Attempt: 2
2RRo4C2KvQwHnvBTpHLtUJHtSoNyiB1kxzk42Exb7CavYrj6r1Fycw3oZse1uksW4WXobBceoFsgmHkevPueosv1
Confirms: [None, None, None]
Confirms: [None, None, None]
Confirms: [None, None, None]
Confirms: [None, None, None]
Transaction did not land
Attempt: 3
fEcGgBBwfVPLSNqn4TfvggqDmHUW1PA6F7HJs2EMrJiLUNdeFZ8bMc66Abp5jmwQ5fDSFpjgApKq6jksnk8Mvkk
Confirms: [None, None, None, None]
Confirms: [None, None, None, None]
Confirms: [None, None, None, None]
Confirms: [None, None, None, None]
Transaction did not land
Attempt: 4
53tX9qDZuHKC5BtAZu4KFRikXvzuLhg47DqUu5GhHiDxNLMPiJ5Uwfh5bceVXnXyk1pVBZGXFaW4DC7PdE7qpiDx
Confirms: [None, None, None, None, None]
Confirms: [None, None, None, None, None]
Confirms: [None, None, None, None, None]
Confirms: [None, None, None, None, None]
Transaction did not land
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ore-cli-0.4.2/src/register.rs:27:14:
Transaction failed: Error { request: None, kind: Custom("Max retries") }
```

**Comment by Banksy-said-hi** [comment]
Same issue!

**Comment by shadowzoom** [comment]
I have the same issue. Does anybody know how to fix this?
Im on mac, latest OS
